export enum Tracos {
  ANAO = 1,
  ELFO = 2,
  HUMANO = 3,
  ACUIDADE = 4,
  AGIL = 5,
  ARREMESSO = 6,
  VERSATIL_CT = 7,
  VERSATIL_P = 8,
  AMPLITUDE = 9,
  CONFORTAVEL = 10,
  BARULHENTA =11,
  FLEXIVEL=12,
  GERAL=13,
  PERICIA=14,
  ATAQUE=15,
  MANUSEIO=16,
  MOVIMENTO=17
}
